name: EnderPearlLogger
version: 1.0
main: com.flyerzrule.enderpearl_logger.EnderPearlLogger
api-version: 1.18
description: A plugin to log every time a player uses an ender pearl and the distance traveled.
